"""The default Behave implementation. Will run all hooks defined here."""

from license_sentinel.analyzer.license_compatibility_analyzer \
    import LicenseCompatibilityAnalyzer as LCA

def before_feature(context, feature):
    """Ensure a one-time setup is performed against every feature 
    that needs it.

    Args:
        context : the context, generated by Behave
        feature: the feature, generated by Behave
    """
    if 'requires_license_list' in feature.tags:
        context.execute_steps('''
            Given a list of licenses
        ''')
        context.lca = LCA()
