# Appends coverage report summary to any push/PR which uses coverage testing
# Will only execute if report generation worked
name: 'Append coverage report'
on:
  workflow_run:
    workflows: ['Create coverage']
    branches:
        - master
        - main
    types: ['completed']
    
jobs:
    on-success:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
        # run if both: a report was generated AND the report file exists
        if: ${{ (github.event.workflow_run.conclusion == 'success') && (hashFiles('test/reports/coverage-${{ matrix.python-version }}.xml') != '')}}
        steps:
          - name: 'Append report'
            uses: kamilok04/coverage-with-title@main
            with:
                coverageFile: test/reports/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}
                title: 'Python (${{ matrix.python-version }}) Coverage Report'
                thresholdAll: 0.8
