# This workflow will install Python dependencies, run unit tests and create a coverage report
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Create coverage

on:
  push:
    branches: [ "main", "develop", "automate-coverage-testing"]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ${{ fromJSON(vars.PYTHON_VERSIONS) }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache-venv
      with:
        path: ./.venv/
        key: ${{ runner.os }}-venv-${{ matrix.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: ${{ runner.os }}-venv-${{ matrix.python-version }}-
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install venv on cache miss
      run: python src/scripts/venv_setup.py --recreate
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Measure coverage with coverage
      run: |
        . ./.venv/bin/activate
        coverage run -m unittest discover
    - name: Create a report for further analysis
      run: |
        . ./.venv/bin/activate
        coverage xml -o test/reports/coverage-${{ matrix.python-version }}.xml
    - name: Extract branch name
      shell: bash
      run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
      id: extract_branch
    - name: Commit a report to the repo
      uses: EndBug/add-and-commit@v9
      with:
        new_branch: ${{ steps.extract_branch.outputs.branch }} # push to branch that pr comes FROM, not the target
        default_author: github_actions
        # The file is in the .gitignore
        # This prevents local reports from leaking into the repo
        add: |
          - test/reports/coverage-${{ matrix.python-version }}.xml --force
        message: 'Append a coverage report'
    - name: Check coverage file exists
      run: if [ ! -f test/reports/coverage-${{ matrix.python-version }}.xml ]; then echo "Coverage file not found"; exit 1; fi
    - name: 'Append report'
      uses: kamilok04/coverage-with-title@main
      with:
        coverageFile: test/reports/coverage-${{ matrix.python-version }}.xml
        token: ${{ secrets.GITHUB_TOKEN }}
        title: 'Python (${{ matrix.python-version }}) Coverage Report'
        thresholdAll: 0.8

