name: Pylint

on: [push]

jobs:
  setup-venv:
    uses: ./.github/workflows/setup-venv.yml
    with:
      python-version: ${{ matrix.python-version }}
  build:
    needs: setup-venv
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
    - uses: actions/checkout@v4
    - name: Analysing the code with pylint
      run: |
        . ./.venv/bin/activate && pylint src --source-roots=.
