name: Setup venv with cache

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      id: cache-venv
      with:
        path: |
          ./.venv/
        key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install venv on cache miss
      run: python src/scripts/venv_setup.py --recreate
      if: steps.cache-venv.outputs.cache-hit != 'true'
    - name: Ensure a venv exists
      # This will do nothing if venv has just been recreated.
      run: python src/scripts/venv_setup.py
      if: steps.cache-venv.outputs.cache-hit == 'true'
    - name: Upload venv artifact
      uses: actions/upload-artifact@v4
      with:
        name: venv-${{ inputs.python-version }}
        path: ./.venv/**
